apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: ap-south-1

vpc:
  id: "vpc-048e31bbc34e193ce"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-south-1b: { id: subnet-0c13c484642404cc5 }
      ap-south-1c: { id: subnet-028ca3336f76387af }
      ap-south-1a: { id: subnet-08b1e8def24a8abdc }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    tags:
      Name: ng-spot
